### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by StarpTech** [hapijs/good#341]
Hi
when I run some tests with (lab) one after the other a `warning` is thrown.
I have one reporter: `good-console` Also when I comment that out and use a different reporter like `good-file` the warning is thrown so it must be a good or nodejs issue.

```
  .........(node) warning: possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:179:15)
    at WriteStream.Readable.on (_stream_readable.js:671:33)
    at WriteStream.once (events.js:204:8)
    at DestroyableTransform.Readable.pipe (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good-console\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:581:8)
    at internals.GoodConsole.init (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good-console\lib\index.js:97:9)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\monitor.js:149:18
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Monitor.start (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\monitor.js:124:11)
    at Object.exports.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\index.js:17:20)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:242:14
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Plugin.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:224:11)
    at Object.exports.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\lib\index.js:71:10)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:242:14
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Plugin.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:224:11)
    at Object.exports.initServer (E:\Vagrant\Ubuntu1404\Test-WebApp\api\test\_utils.js:199:10)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\test\auth\link-accounts.js:303:11
    at Immediate._onImmediate (C:\Users\dustin\AppData\Roaming\npm\node_modules\lab\lib\runner.js:445:17)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
.(node) warning: possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:179:15)
    at WriteStream.Readable.on (_stream_readable.js:671:33)
    at DestroyableTransform.Readable.pipe (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good-console\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:516:8)
    at internals.GoodConsole.init (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good-console\lib\index.js:97:9)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\monitor.js:149:18
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Monitor.start (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\monitor.js:124:11)
    at Object.exports.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\index.js:17:20)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:242:14
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Plugin.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:224:11)
    at Object.exports.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\lib\index.js:71:10)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:242:14
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Plugin.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:224:11)
    at Object.exports.initServer (E:\Vagrant\Ubuntu1404\Test-WebApp\api\test\_utils.js:199:10)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\test\auth\local-reset-password.js:16:11
    at Immediate._onImmediate (C:\Users\dustin\AppData\Roaming\npm\node_modules\lab\lib\runner.js:445:17)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
(node) warning: possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:179:15)
    at WriteStream.Readable.on (_stream_readable.js:671:33)
    at DestroyableTransform.Readable.pipe (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good-console\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:531:8)
    at internals.GoodConsole.init (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good-console\lib\index.js:97:9)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\monitor.js:149:18
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Monitor.start (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\monitor.js:124:11)
    at Object.exports.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\index.js:17:20)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:242:14
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Plugin.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:224:11)
    at Object.exports.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\lib\index.js:71:10)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:242:14
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Plugin.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:224:11)
    at Object.exports.initServer (E:\Vagrant\Ubuntu1404\Test-WebApp\api\test\_utils.js:199:10)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\test\auth\local-reset-password.js:16:11
    at Immediate._onImmediate (C:\Users\dustin\AppData\Roaming\npm\node_modules\lab\lib\runner.js:445:17)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:179:15)
    at WriteStream.Readable.on (_stream_readable.js:671:33)
    at WriteStream.once (events.js:204:8)
    at DestroyableTransform.Readable.pipe (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good-console\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:576:8)
    at internals.GoodConsole.init (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good-console\lib\index.js:97:9)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\monitor.js:149:18
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Monitor.start (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\monitor.js:124:11)
    at Object.exports.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\index.js:17:20)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:242:14
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Plugin.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:224:11)
    at Object.exports.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\lib\index.js:71:10)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:242:14
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Plugin.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:224:11)
    at Object.exports.initServer (E:\Vagrant\Ubuntu1404\Test-WebApp\api\test\_utils.js:199:10)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\test\auth\local-reset-password.js:16:11
    at Immediate._onImmediate (C:\Users\dustin\AppData\Roaming\npm\node_modules\lab\lib\runner.js:445:17)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
(node) warning: possible EventEmitter memory leak detected. 11 response listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:179:15)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\monitor.js:172:15
    at done (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:30:25)
    at internals.GoodConsole.init (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good-console\lib\index.js:99:5)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\monitor.js:149:18
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Monitor.start (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\monitor.js:124:11)
    at Object.exports.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\good\lib\index.js:17:20)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:242:14
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Plugin.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:224:11)
    at Object.exports.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\lib\index.js:71:10)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:242:14
    at iterate (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Plugin.register (E:\Vagrant\Ubuntu1404\Test-WebApp\api\node_modules\hapi\lib\plugin.js:224:11)
    at Object.exports.initServer (E:\Vagrant\Ubuntu1404\Test-WebApp\api\test\_utils.js:199:10)
    at E:\Vagrant\Ubuntu1404\Test-WebApp\api\test\auth\local-reset-password.js:16:11
    at Immediate._onImmediate (C:\Users\dustin\AppData\Roaming\npm\node_modules\lab\lib\runner.js:445:17)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```
good: 6.1.2,
good-console: 5.0.0
hapi: 8.4.0
NodeJs: v0.12.2

thanks!

**Comment by StarpTech** [comment]
I think it can be closed. Answered in https://github.com/cbarrick/gulp-run/issues/7

**Comment by eventhough** [comment]
@StarpTech Did you ever figure out how to suppress these warning messages?

**Comment by indieforger** [comment]
@StarpTech Did you ever figure out how to suppress these warning messages?

**Comment by arb** [comment]
See related issue here https://github.com/hapijs/good/pull/435

**Comment by indieforger** [comment]
Thanks @arb
